<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<groupId>6b51a7a5-4bc2-41a6-bd30-1a4a21806135</groupId>
	<artifactId>product-api-impl</artifactId>
	<version>1.0.11</version>
	<packaging>mule-application</packaging>

	<name>product-api</name>

	<properties>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>

		<app.runtime>4.9.5</app.runtime>
		<mule.maven.plugin.version>4.8.0</mule.maven.plugin.version>
		<munit.version>3.2.1</munit.version>
	</properties>

	<build>
		<plugins>
			<plugin>
				<groupId>org.mule.tools.maven</groupId>
				<artifactId>mule-maven-plugin</artifactId>
				<version>${mule.maven.plugin.version}</version>
				<extensions>true</extensions>
				<configuration>
					<cloudhub2Deployment>
						<uri>https://anypoint.mulesoft.com</uri>
						<provider>MC</provider>
						<businessGroupId>6b51a7a5-4bc2-41a6-bd30-1a4a21806135</businessGroupId>
						<connectedAppClientId>e1ff626ac78a40a1b657be5d61051f2c</connectedAppClientId>
						<connectedAppClientSecret>EfB56dcCFC1c478681BE9819d3b20Fc3</connectedAppClientSecret>
						<connectedAppGrantType>client_credentials</connectedAppGrantType>
						<environment>test</environment>
						<applicationName>anu-test-product-api</applicationName>
						<target>Cloudhub-US-East-2</target>
						<muleVersion>4.9.5</muleVersion>
						<releaseChannel>LTS</releaseChannel>
						<javaVersion>17</javaVersion>
						<replicas>1</replicas>
						<vCores>0.1</vCores>
						<deploymentSettings>
							<generateDefaultPublicUrl>true</generateDefaultPublicUrl>
						</deploymentSettings>
						<properties>
							<http.port>8081</http.port>
							<env>test</env>
							<api.id>21011602</api.id>
							<anypoint.platform.client_id>${anypoint.platform.client_id}</anypoint.platform.client_id>
							<anypoint.platform.client_secret>${anypoint.platform.client_secret}</anypoint.platform.client_secret>
							<anypoint.platform.base_uri>https://anypoint.mulesoft.com</anypoint.platform.base_uri>
							<anypoint.platform.analytics_base_uri>https://analytics-ingest.anypoint.mulesoft.com</anypoint.platform.analytics_base_uri>
						</properties>
					</cloudhub2Deployment>
				</configuration>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-clean-plugin</artifactId>
				<version>3.2.0</version>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-deploy-plugin</artifactId>
				<version>3.1.1</version>
				<executions>
					<execution>
						<id>publish-to-exchange</id>
						<phase>deploy</phase>
						<goals>
							<goal>deploy</goal>
						</goals>
					</execution>
				</executions>
			</plugin>

			<plugin>
				<groupId>com.mulesoft.munit.tools</groupId>
				<artifactId>munit-maven-plugin</artifactId>
				<version>${munit.version}</version>
				<executions>
					<execution>
						<id>test</id>
						<phase>test</phase>
						<goals>
							<goal>test</goal>
						</goals>
					</execution>
				</executions>
			</plugin>
		</plugins>
	</build>

	<dependencies>
		<dependency>
			<groupId>org.mule.connectors</groupId>
			<artifactId>mule-http-connector</artifactId>
			<version>1.11.1</version>
			<classifier>mule-plugin</classifier>
		</dependency>
		<dependency>
			<groupId>org.mule.connectors</groupId>
			<artifactId>mule-sockets-connector</artifactId>
			<version>1.2.7</version>
			<classifier>mule-plugin</classifier>
		</dependency>
		<dependency>
			<groupId>org.mule.modules</groupId>
			<artifactId>mule-apikit-module</artifactId>
			<version>1.11.11</version>
			<classifier>mule-plugin</classifier>
		</dependency>
		<dependency>
			<groupId>com.mulesoft.munit</groupId>
			<artifactId>munit-runner</artifactId>
			<version>${munit.version}</version>
			<classifier>mule-plugin</classifier>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>com.mulesoft.munit</groupId>
			<artifactId>munit-tools</artifactId>
			<version>${munit.version}</version>
			<classifier>mule-plugin</classifier>
			<scope>test</scope>
		</dependency>
	</dependencies>

	<repositories>
		<repository>
			<id>anypoint-exchange-v3</id>
			<name>Anypoint Exchange</name>
			<url>https://maven.anypoint.mulesoft.com/api/v3/maven</url>
			<layout>default</layout>
		</repository>
		<repository>
			<id>mulesoft-releases</id>
			<name>MuleSoft Releases Repository</name>
			<url>https://repository.mulesoft.org/nexus/repository/releases/</url>
			<layout>default</layout>
		</repository>
	</repositories>

	<pluginRepositories>
		<pluginRepository>
			<id>mulesoft-releases</id>
			<name>MuleSoft Releases Repository</name>
			<layout>default</layout>
			<url>https://repository.mulesoft.org/nexus/repository/releases/</url>
			<snapshots>
				<enabled>false</enabled>
			</snapshots>
		</pluginRepository>
	</pluginRepositories>

	<distributionManagement>
		<repository>
			<id>anypoint-exchange-v3</id>
			<name>Anypoint Exchange</name>
			<url>https://maven.anypoint.mulesoft.com/api/v3/organizations/6b51a7a5-4bc2-41a6-bd30-1a4a21806135/maven</url>
			<layout>default</layout>
		</repository>
	</distributionManagement>
</project>