#%RAML 1.0
title: product-api
baseUri: http://localhost:8081/products
/products:
  get:
    description: to get products
    responses:
      200:
        body:
          application/json:
            example:
              {
                "productsID": "12345",
                "productName": "Atomic energy",
                "productProvider": "India",
                "productDescription": "Atomic energy creater"
              }

